// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PosLedger.Api.Persistence;

#nullable disable

namespace PosLedger.Api.Persistence.Migrations
{
    [DbContext(typeof(PosLedgerDbContext))]
    [Migration("20260806181144_ImportsAndReportingIndex")]
    partial class ImportsAndReportingIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("sale_number_seq");

            modelBuilder.Entity("PosLedger.Api.Domain.IdempotencyRecord", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("endpoint");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_body");

                    b.Property<int>("ResponseStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_status_code");

                    b.Property<Guid?>("SaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_id");

                    b.HasKey("Key")
                        .HasName("pk_idempotency_records");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_idempotency_records_created_at");

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("PosLedger.Api.Domain.ImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("file_name");

                    b.Property<int>("RowsAccepted")
                        .HasColumnType("integer")
                        .HasColumnName("rows_accepted");

                    b.Property<int>("RowsRead")
                        .HasColumnType("integer")
                        .HasColumnName("rows_read");

                    b.Property<int>("RowsRejected")
                        .HasColumnType("integer")
                        .HasColumnName("rows_rejected");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id")
                        .HasName("pk_import_batches");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_import_batches_created_at");

                    b.ToTable("import_batches", (string)null);
                });

            modelBuilder.Entity("PosLedger.Api.Domain.ImportError", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<string>("RawLine")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("raw_line");

                    b.Property<string>("Rule")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("rule");

                    b.HasKey("Id")
                        .HasName("pk_import_errors");

                    b.HasIndex("BatchId", "Rule")
                        .HasDatabaseName("ix_import_errors_batch_id_rule");

                    b.ToTable("import_errors", (string)null);
                });

            modelBuilder.Entity("PosLedger.Api.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku");

                    b.Property<int>("StockOnHand")
                        .HasColumnType("integer")
                        .HasColumnName("stock_on_hand");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_products_name");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("ix_products_sku");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("ck_products_price_non_negative", "unit_price >= 0");

                            t.HasCheckConstraint("ck_products_stock_non_negative", "stock_on_hand >= 0");
                        });
                });

            modelBuilder.Entity("PosLedger.Api.Domain.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CashierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cashier_name");

                    b.Property<long>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("number")
                        .HasDefaultValueSql("nextval('sale_number_seq')");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("pk_sales");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_sales_number");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_sales_occurred_at");

                    b.ToTable("sales", null, t =>
                        {
                            t.HasCheckConstraint("ck_sales_total_non_negative", "total >= 0");
                        });
                });

            modelBuilder.Entity("PosLedger.Api.Domain.SaleLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("line_total");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_id");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_sale_lines");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_sale_lines_product_id");

                    b.HasIndex("SaleId")
                        .HasDatabaseName("ix_sale_lines_sale_id");

                    b.ToTable("sale_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_sale_lines_quantity_positive", "quantity > 0");

                            t.HasCheckConstraint("ck_sale_lines_total_matches", "line_total = unit_price * quantity");
                        });
                });

            modelBuilder.Entity("PosLedger.Api.Domain.StockMovement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<int>("Delta")
                        .HasColumnType("integer")
                        .HasColumnName("delta");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Reason")
                        .HasColumnType("integer")
                        .HasColumnName("reason");

                    b.Property<string>("Reference")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reference");

                    b.HasKey("Id")
                        .HasName("pk_stock_movements");

                    b.HasIndex("OccurredAt", "Reason")
                        .HasDatabaseName("ix_stock_movements_occurred_at_reason");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("OccurredAt", "Reason"), new[] { "ProductId", "Delta" });

                    b.HasIndex("ProductId", "OccurredAt")
                        .HasDatabaseName("ix_stock_movements_product_id_occurred_at");

                    b.ToTable("stock_movements", null, t =>
                        {
                            t.HasCheckConstraint("ck_stock_movements_delta_not_zero", "delta <> 0");
                        });
                });

            modelBuilder.Entity("PosLedger.Api.Domain.ImportError", b =>
                {
                    b.HasOne("PosLedger.Api.Domain.ImportBatch", null)
                        .WithMany("Errors")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_import_errors_import_batches_batch_id");
                });

            modelBuilder.Entity("PosLedger.Api.Domain.SaleLine", b =>
                {
                    b.HasOne("PosLedger.Api.Domain.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sale_lines_products_product_id");

                    b.HasOne("PosLedger.Api.Domain.Sale", null)
                        .WithMany("Lines")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sale_lines_sales_sale_id");
                });

            modelBuilder.Entity("PosLedger.Api.Domain.StockMovement", b =>
                {
                    b.HasOne("PosLedger.Api.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_movements_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PosLedger.Api.Domain.ImportBatch", b =>
                {
                    b.Navigation("Errors");
                });

            modelBuilder.Entity("PosLedger.Api.Domain.Sale", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
